name: .NET

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.0'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build "GymHelper.sln"  --configuration Release
    - name: Test
      run: dotnet test "GymHelper.sln" --verbosity normal
