name: Xamarin CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:        
  Android:
    runs-on: windows-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 'true'
    steps:
    - uses: actions/checkout@v1
    - uses: warrenbuckley/Setup-MSBuild@v1
    - name: Android
      shell: pwsh
      run: |
        dotnet tool install --global boots
        boots --preview XamarinAndroid
        cd GymHelper
        cd GymHelper.Android       
        msbuild GymHelper.Android.csproj /restore /t:SignAndroidPackage
